// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzFj0yWkb-DPj54Eb7TqfUCoFOQfd97HI',
    appId: '1:1034986222901:web:68114e37bf94ef9045487c',
    messagingSenderId: '1034986222901',
    projectId: 'notes-2ed28',
    authDomain: 'notes-2ed28.firebaseapp.com',
    storageBucket: 'notes-2ed28.firebasestorage.app',
    measurementId: 'G-63K41T32ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2zYSRkl36s83SaZX3pxd4CCOFmMpMjso',
    appId: '1:1034986222901:android:0a670059a6626b2845487c',
    messagingSenderId: '1034986222901',
    projectId: 'notes-2ed28',
    storageBucket: 'notes-2ed28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB07_oznCVF4Fzg2FhzwR2_mFhLrhtSvrM',
    appId: '1:1034986222901:ios:b08b6f7d5f3d041745487c',
    messagingSenderId: '1034986222901',
    projectId: 'notes-2ed28',
    storageBucket: 'notes-2ed28.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB07_oznCVF4Fzg2FhzwR2_mFhLrhtSvrM',
    appId: '1:1034986222901:ios:b08b6f7d5f3d041745487c',
    messagingSenderId: '1034986222901',
    projectId: 'notes-2ed28',
    storageBucket: 'notes-2ed28.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFj0yWkb-DPj54Eb7TqfUCoFOQfd97HI',
    appId: '1:1034986222901:web:bcdacc8a0a34ff5045487c',
    messagingSenderId: '1034986222901',
    projectId: 'notes-2ed28',
    authDomain: 'notes-2ed28.firebaseapp.com',
    storageBucket: 'notes-2ed28.firebasestorage.app',
    measurementId: 'G-5EZTVPEDPL',
  );
}
