// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEHb3O0teO1lXhaC3OadrXzOnAiqqr08',
    appId: '1:662281939563:web:01f83ba630bc482daa5f2e',
    messagingSenderId: '662281939563',
    projectId: 'daftarbelanja-4bb10',
    authDomain: 'daftarbelanja-4bb10.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-4bb10-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-4bb10.firebasestorage.app',
    measurementId: 'G-Y9QG5YMPDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADpM0l5FslG6Y1-QfVzABxuu-wnhXptEw',
    appId: '1:662281939563:android:7559b16fdf8d4d5daa5f2e',
    messagingSenderId: '662281939563',
    projectId: 'daftarbelanja-4bb10',
    databaseURL: 'https://daftarbelanja-4bb10-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-4bb10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiT_yDkgTldNnnclcKWKn-15fzFjbBzoE',
    appId: '1:662281939563:ios:4e8a182d3e44686baa5f2e',
    messagingSenderId: '662281939563',
    projectId: 'daftarbelanja-4bb10',
    databaseURL: 'https://daftarbelanja-4bb10-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-4bb10.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiT_yDkgTldNnnclcKWKn-15fzFjbBzoE',
    appId: '1:662281939563:ios:4e8a182d3e44686baa5f2e',
    messagingSenderId: '662281939563',
    projectId: 'daftarbelanja-4bb10',
    databaseURL: 'https://daftarbelanja-4bb10-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-4bb10.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDEHb3O0teO1lXhaC3OadrXzOnAiqqr08',
    appId: '1:662281939563:web:d9b0024d44707d0daa5f2e',
    messagingSenderId: '662281939563',
    projectId: 'daftarbelanja-4bb10',
    authDomain: 'daftarbelanja-4bb10.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-4bb10-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-4bb10.firebasestorage.app',
    measurementId: 'G-84VCVGJG5G',
  );
}
