// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgqqbMaJ9wkNIz_Vt3MhpjgRHz3K2RfqE',
    appId: '1:887036411142:web:873f6f589dd2cc08967287',
    messagingSenderId: '887036411142',
    projectId: 'mdpgold-a6e29',
    authDomain: 'mdpgold-a6e29.firebaseapp.com',
    databaseURL: 'https://mdpgold-a6e29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-a6e29.firebasestorage.app',
    measurementId: 'G-4XM6HVE32S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpGymAjCGryqpNCdE_rbtHPwMy1lT3czw',
    appId: '1:887036411142:android:cd7685451d019de3967287',
    messagingSenderId: '887036411142',
    projectId: 'mdpgold-a6e29',
    databaseURL: 'https://mdpgold-a6e29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-a6e29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXplpDtdnw1S1WXHjNzw-2Jg2OVEOxvHE',
    appId: '1:887036411142:ios:fcbd467006a79d53967287',
    messagingSenderId: '887036411142',
    projectId: 'mdpgold-a6e29',
    databaseURL: 'https://mdpgold-a6e29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-a6e29.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXplpDtdnw1S1WXHjNzw-2Jg2OVEOxvHE',
    appId: '1:887036411142:ios:fcbd467006a79d53967287',
    messagingSenderId: '887036411142',
    projectId: 'mdpgold-a6e29',
    databaseURL: 'https://mdpgold-a6e29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-a6e29.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgqqbMaJ9wkNIz_Vt3MhpjgRHz3K2RfqE',
    appId: '1:887036411142:web:5c98ba51ab38b613967287',
    messagingSenderId: '887036411142',
    projectId: 'mdpgold-a6e29',
    authDomain: 'mdpgold-a6e29.firebaseapp.com',
    databaseURL: 'https://mdpgold-a6e29-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mdpgold-a6e29.firebasestorage.app',
    measurementId: 'G-N8EJKXQVY3',
  );
}
